package main
import(
	"fmt"
    "reflect"
    "bytes"
    "net"
    "net/http"
    "net/url"
    "bufio"
    "strings"
    "strconv"
    "encoding/asn1"
    "encoding/json"
    "github.com/456vv/vmap/v2"
    "github.com/456vv/vconnpool"
    "github.com/456vv/vbody"
    "github.com/456vv/vcipher"
    "github.com/456vv/vweb"
    "regexp"
    "unicode"
    "unicode/utf8"
    "os"
    "io"
    "io/ioutil"
    "context"
    "time"
    "crypto"
    "crypto/aes"
    "crypto/cipher"
    "crypto/des"
    "crypto/dsa"
    "crypto/ecdsa"
    "crypto/elliptic"
    "crypto/hmac"
    "crypto/rand"
    "crypto/rsa"
    "crypto/tls"
    "crypto/x509"
    "crypto/x509/pkix"
    "crypto/sha1"
    "crypto/sha256"
    "crypto/sha512"
    "math/big"
    "unsafe"
    "path/filepath"
    "path"
   	"sync"
   	"sync/atomic"
   	"errors"
)

var dotFuncMap = map[string]map[string]interface{}{
	"vweb":{
		"ConfigSitePlugin":func(inf interface{}) *vweb.ConfigSitePlugin {if inf == nil {return new(vweb.ConfigSitePlugin)};switch v := inf.(type){case *vweb.ConfigSitePlugin:return v;case vweb.ConfigSitePlugin:return &v;default:if t, ok := inf.(*vweb.ConfigSitePlugin); ok {return t}else if t, ok := inf.(vweb.ConfigSitePlugin); ok {return &t};return (*vweb.ConfigSitePlugin)(nil)}},
		"PluginHTTPClient":func(inf interface{}) *vweb.PluginHTTPClient {if inf == nil {return new(vweb.PluginHTTPClient)};switch v := inf.(type){case *vweb.PluginHTTPClient:return v;case vweb.PluginHTTPClient:return &v;default:if t, ok := inf.(*vweb.PluginHTTPClient); ok {return t}else if t, ok := inf.(vweb.PluginHTTPClient); ok {return &t};return (*vweb.PluginHTTPClient)(nil)}},
		"ConfigPluginHTTPClient":vweb.ConfigPluginHTTPClient,
		"PluginRPCClient":func(inf interface{}) *vweb.PluginRPCClient {if inf == nil {return new(vweb.PluginRPCClient)};switch v := inf.(type){case *vweb.PluginRPCClient:return v;case vweb.PluginRPCClient:return &v;default:if t, ok := inf.(*vweb.PluginRPCClient); ok {return t}else if t, ok := inf.(vweb.PluginRPCClient); ok {return &t};return (*vweb.PluginRPCClient)(nil)}},
		"ConfigPluginRPCClient":vweb.ConfigPluginRPCClient,
		"GenerateRandomId":vweb.GenerateRandomId,
		"GenerateRandom":vweb.GenerateRandom,
		"GenerateRandomString":vweb.GenerateRandomString,
		"AddSalt":vweb.AddSalt,
		"PagePath":vweb.PagePath,
		"Cookie":func(inf interface{}) *vweb.Cookie {if inf == nil {return new(vweb.Cookie)};switch v := inf.(type){case *vweb.Cookie:return v;case vweb.Cookie:return &v;default:if t, ok := inf.(*vweb.Cookie); ok {return t}else if t, ok := inf.(vweb.Cookie); ok {return &t};return (*vweb.Cookie)(nil)}},
		"Session":func(inf interface{}) *vweb.Session {if inf == nil {return new(vweb.Session)};switch v := inf.(type){case *vweb.Session:return v;case vweb.Session:return &v;default:if t, ok := inf.(*vweb.Session); ok {return t}else if t, ok := inf.(vweb.Session); ok {return &t};return (*vweb.Session)(nil)}},
		"NewSession":vweb.NewSession,
		"Sessions":func(inf interface{}) *vweb.Sessions {if inf == nil {return new(vweb.Sessions)};switch v := inf.(type){case *vweb.Sessions:return v;case vweb.Sessions:return &v;default:if t, ok := inf.(*vweb.Sessions); ok {return t}else if t, ok := inf.(vweb.Sessions); ok {return &t};return (*vweb.Sessions)(nil)}},
		"SitePool":func(inf interface{}) *vweb.SitePool {if inf == nil {return new(vweb.SitePool)};switch v := inf.(type){case *vweb.SitePool:return v;case vweb.SitePool:return &v;default:if t, ok := inf.(*vweb.SitePool); ok {return t}else if t, ok := inf.(vweb.SitePool); ok {return &t};return (*vweb.SitePool)(nil)}},
		"NewSitePool":vweb.NewSitePool,
		"Site":func(inf interface{}) *vweb.Site {if inf == nil {return new(vweb.Site)};switch v := inf.(type){case *vweb.Site:return v;case vweb.Site:return &v;default:if t, ok := inf.(*vweb.Site); ok {return t}else if t, ok := inf.(vweb.Site); ok {return &t};return (*vweb.Site)(nil)}},
		"NewSite":vweb.NewSite,
		"Sites":func(inf interface{}) *vweb.Sites {if inf == nil {return new(vweb.Sites)};switch v := inf.(type){case *vweb.Sites:return v;case vweb.Sites:return &v;default:if t, ok := inf.(*vweb.Sites); ok {return t}else if t, ok := inf.(vweb.Sites); ok {return &t};return (*vweb.Sites)(nil)}},
		"NewSites":vweb.NewSites,
		"ServerHandlerStatic":func(inf interface{}) *vweb.ServerHandlerStatic {if inf == nil {return new(vweb.ServerHandlerStatic)};switch v := inf.(type){case *vweb.ServerHandlerStatic:return v;case vweb.ServerHandlerStatic:return &v;default:if t, ok := inf.(*vweb.ServerHandlerStatic); ok {return t}else if t, ok := inf.(vweb.ServerHandlerStatic); ok {return &t};return (*vweb.ServerHandlerStatic)(nil)}},
		"ServerHandlerDynamic":func(inf interface{}) *vweb.ServerHandlerDynamic {if inf == nil {return new(vweb.ServerHandlerDynamic)};switch v := inf.(type){case *vweb.ServerHandlerDynamic:return v;case vweb.ServerHandlerDynamic:return &v;default:if t, ok := inf.(*vweb.ServerHandlerDynamic); ok {return t}else if t, ok := inf.(vweb.ServerHandlerDynamic); ok {return &t};return (*vweb.ServerHandlerDynamic)(nil)}},
	},
	"vconnpool":{
		"ConnPool":func(inf interface{}) *vconnpool.ConnPool {if inf == nil {return new(vconnpool.ConnPool)};switch v := inf.(type){case *vconnpool.ConnPool:return v;case vconnpool.ConnPool:return &v;default:if t, ok := inf.(*vconnpool.ConnPool); ok {return t}else if t, ok := inf.(vconnpool.ConnPool); ok {return &t};return (*vconnpool.ConnPool)(nil)}},
	},
	"vbody":{
		"NewReader":vbody.NewReader,
		"NewWriter":vbody.NewWriter,
	},
	"vcipher":{
		"AES":vcipher.AES,
		"NewCipher":vcipher.NewCipher,
	},
	"vmap":{
		"NewMap":vmap.NewMap,
	},
	"errors":{
		"As":errors.As,
		"Is":errors.Is,
		"New":errors.New,
		"Unwrap":errors.Unwrap,
	},
	"sync":{
		"Map":func(inf interface{}) *sync.Map {if inf == nil {return new(sync.Map)};switch v := inf.(type){case *sync.Map:return v;case sync.Map:return &v;default:if t, ok := inf.(*sync.Map); ok {return t}else if t, ok := inf.(sync.Map); ok {return &t};return (*sync.Map)(nil)}},
	},
	"sync/atomic":{
		"AddInt32":atomic.AddInt32,
		"AddInt64":atomic.AddInt64,
		"AddUint32":atomic.AddUint32,
		"AddUint64":atomic.AddUint64,
		"AddUintptr":atomic.AddUintptr,
		"CompareAndSwapInt32":atomic.CompareAndSwapInt32,
		"CompareAndSwapInt64":atomic.CompareAndSwapInt64,
		"CompareAndSwapPointer":atomic.CompareAndSwapPointer,
		"CompareAndSwapUint32":atomic.CompareAndSwapUint32,
		"CompareAndSwapUint64":atomic.CompareAndSwapUint64,
		"CompareAndSwapUintptr":atomic.CompareAndSwapUintptr,
		"LoadInt32":atomic.LoadInt32,
		"LoadInt64":atomic.LoadInt64,
		"LoadPointer":atomic.LoadPointer,
		"LoadUint32":atomic.LoadUint32,
		"LoadUint64":atomic.LoadUint64,
		"LoadUintptr":atomic.LoadUintptr,
		"StoreInt32":atomic.StoreInt32,
		"StoreInt64":atomic.StoreInt64,
		"StorePointer":atomic.StorePointer,
		"StoreUint32":atomic.StoreUint32,
		"StoreUint64":atomic.StoreUint64,
		"StoreUintptr":atomic.StoreUintptr,
		"SwapInt32":atomic.SwapInt32,
		"SwapInt64":atomic.SwapInt64,
		"SwapPointer":atomic.SwapPointer,
		"SwapUint32":atomic.SwapUint32,
		"SwapUint64":atomic.SwapUint64,
		"SwapUintptr":atomic.SwapUintptr,
		"Value":func(inf interface{}) *atomic.Value {if inf == nil {return new(atomic.Value)};switch v := inf.(type){case *atomic.Value:return v;case atomic.Value:return &v;default:if t, ok := inf.(*atomic.Value); ok {return t}else if t, ok := inf.(atomic.Value); ok {return &t};return (*atomic.Value)(nil)}},
	},
	"path":{
		"Base":path.Base,
		"Clean":path.Clean,
		"Dir":path.Dir,
		"Ext":path.Ext,
		"IsAbs":path.IsAbs,
		"Join":path.Join,
		"Split":path.Split,
		"Match":path.Match,
	},
	"path/filepath":{
		"Separator":filepath.Separator,
		"ListSeparator":filepath.ListSeparator,
		"Abs":filepath.Abs,
		"Rel":filepath.Rel,
		"Base":filepath.Base,
		"Clean":filepath.Clean,
		"Dir":filepath.Dir,
		"EvalSymlinks":filepath.EvalSymlinks,
		"Ext":filepath.Ext,
		"FromSlash":filepath.FromSlash,
		"ToSlash":filepath.ToSlash,
		"Glob":filepath.Glob,
		"HasPrefix":filepath.HasPrefix,
		"IsAbs":filepath.IsAbs,
		"Join":filepath.Join,
		"Match":filepath.Match,
		"Split":filepath.Split,
		"SplitList":filepath.SplitList,
		"VolumeName":filepath.VolumeName,
	},
	"fmt":{
		"Errorf":fmt.Errorf,
		"Fprint":fmt.Fprint,
		"Fprintf":fmt.Fprintf,
		"Fprintln":fmt.Fprintln,
		"Sprint":fmt.Sprint,
		"Sprintf":fmt.Sprintf,
		"Sprintln":fmt.Sprintln,
	},
    "reflect":{
        "Copy":reflect.Copy,
        "DeepEqual":reflect.DeepEqual,
        "Select":reflect.Select,
        "Swapper":reflect.Swapper,
		"ChanDir":func(ChanDir int) reflect.ChanDir {return reflect.ChanDir(ChanDir)},
        "RecvDir":reflect.RecvDir,
        "SendDir":reflect.SendDir,
        "BothDir":reflect.BothDir,
		"Kind":func(Kind uint) reflect.Kind {return reflect.Kind(Kind)},
        "Invalid":reflect.Invalid,
        "Bool":reflect.Bool,
        "Int":reflect.Int,
        "Int8":reflect.Int8,
        "Int16":reflect.Int16,
        "Int32":reflect.Int32,
        "Int64":reflect.Int64,
        "Uint":reflect.Uint,
        "Uint8":reflect.Uint8,
        "Uint16":reflect.Uint16,
        "Uint32":reflect.Uint32,
        "Uint64":reflect.Uint64,
        "Uintptr":reflect.Uintptr,
        "Float32":reflect.Float32,
        "Float64":reflect.Float64,
        "Complex64":reflect.Complex64,
        "Complex128":reflect.Complex128,
        "Array":reflect.Array,
        "Chan":reflect.Chan,
        "Func":reflect.Func,
        "Interface":reflect.Interface,
        "Map":reflect.Map,
        "Ptr":reflect.Ptr,
        "Slice":reflect.Slice,
        "String":reflect.String,
        "Struct":reflect.Struct,
        "UnsafePointer":reflect.UnsafePointer,
		"Method":func(inf interface{}) *reflect.Method {if inf == nil {return new(reflect.Method)};switch v := inf.(type){case *reflect.Method:return v;case reflect.Method:return &v;default:if t, ok := inf.(*reflect.Method); ok {return t}else if t, ok := inf.(reflect.Method); ok {return &t};return (*reflect.Method)(nil)}},
		"SelectCase":func(inf interface{}) *reflect.SelectCase {if inf == nil {return new(reflect.SelectCase)};switch v := inf.(type){case *reflect.SelectCase:return v;case reflect.SelectCase:return &v;default:if t, ok := inf.(*reflect.SelectCase); ok {return t}else if t, ok := inf.(reflect.SelectCase); ok {return &t};return (*reflect.SelectCase)(nil)}},
		"SelectDir":func(SelectDir int) reflect.SelectDir {return reflect.SelectDir(SelectDir)},
		"SelectSend":reflect.SelectSend,
		"SelectRecv":reflect.SelectRecv,
		"SelectDefault":reflect.SelectDefault,
		"SliceHeader":func(inf interface{}) *reflect.SliceHeader {if inf == nil {return new(reflect.SliceHeader)};switch v := inf.(type){case *reflect.SliceHeader:return v;case reflect.SliceHeader:return &v;default:if t, ok := inf.(*reflect.SliceHeader); ok {return t}else if t, ok := inf.(reflect.SliceHeader); ok {return &t};return (*reflect.SliceHeader)(nil)}},
		"StringHeader":func(inf interface{}) *reflect.StringHeader {if inf == nil {return new(reflect.StringHeader)};switch v := inf.(type){case *reflect.StringHeader:return v;case reflect.StringHeader:return &v;default:if t, ok := inf.(*reflect.StringHeader); ok {return t}else if t, ok := inf.(reflect.StringHeader); ok {return &t};return (*reflect.StringHeader)(nil)}},
		"StructField":func(inf interface{}) *reflect.StructField {if inf == nil {return new(reflect.StructField)};switch v := inf.(type){case *reflect.StructField:return v;case reflect.StructField:return &v;default:if t, ok := inf.(*reflect.StructField); ok {return t}else if t, ok := inf.(reflect.StructField); ok {return &t};return (*reflect.StructField)(nil)}},
		"StructTag":func(StructTag string) reflect.StructTag {return reflect.StructTag(StructTag)},
		"ArrayOf":reflect.ArrayOf,
        "ChanOf":reflect.ChanOf,
        "FuncOf":reflect.FuncOf,
        "MapOf":reflect.MapOf,
        "PtrTo":reflect.PtrTo,
        "SliceOf":reflect.SliceOf,
        "StructOf":reflect.StructOf,
        "TypeOf":reflect.TypeOf,
		"Value":func(inf interface{}) *reflect.Value {if inf == nil {return new(reflect.Value)};switch v := inf.(type){case *reflect.Value:return v;case reflect.Value:return &v;default:if t, ok := inf.(*reflect.Value); ok {return t}else if t, ok := inf.(reflect.Value); ok {return &t};return (*reflect.Value)(nil)}},
        "Append":reflect.Append,
        "AppendSlice":reflect.AppendSlice,
        "Indirect":reflect.Indirect,
        "MakeChan":reflect.MakeChan,
        "MakeFunc":reflect.MakeFunc,
        "MakeMap":reflect.MakeMap,
        "MakeMapWithSize":reflect.MakeMapWithSize,
        "MakeSlice":reflect.MakeSlice,
        "New":reflect.New,
        "NewAt":reflect.NewAt,
        "ValueOf":reflect.ValueOf,
        "Zero":reflect.Zero,
    },
    "unsafe":{
    	"Uintptr":func(Pointer unsafe.Pointer) uintptr {return uintptr(Pointer)},
		"Pointer":func(Pointer uintptr) unsafe.Pointer {return unsafe.Pointer(Pointer)},
		"Alignof":func(Pointer uintptr) uintptr {return unsafe.Alignof(Pointer)},
		"Sizeof":func(Pointer uintptr) uintptr {return unsafe.Sizeof(Pointer)},
    },
    "context":{
		"CancelFunc":func(CancelFunc func()) context.CancelFunc {return context.CancelFunc(CancelFunc)},
    	"Background":context.Background,
    	"TODO":context.TODO,
    	"WithCancel":context.WithCancel,
    	"WithDeadline":context.WithDeadline,
    	"WithTimeout":context.WithTimeout,
    	"WithValue":context.WithValue,
    },
    "time":{
		"ANSIC":time.ANSIC,
		"UnixDate":time.UnixDate,
		"RubyDate":time.RubyDate,
		"RFC822":time.RFC822,
		"RFC822Z":time.RFC822Z,
		"RFC850":time.RFC850,
		"RFC1123":time.RFC1123,
		"RFC1123Z":time.RFC1123Z,
		"RFC3339":time.RFC3339,
		"RFC3339Nano":time.RFC3339Nano,
		"Kitchen":time.Kitchen,
		"Stamp":time.Stamp,
		"StampMilli":time.StampMilli,
		"StampMicro":time.StampMicro,
		"StampNano":time.StampNano,
		"Duration":func(Duration int64) time.Duration {return time.Duration(Duration)},
		"Nanosecond":time.Nanosecond,
		"Microsecond":time.Microsecond,
		"Millisecond":time.Millisecond,
		"Second":time.Second,
		"Minute":time.Minute,
		"Hour":time.Hour,
		"After":time.After,
		"Sleep":time.Sleep,
		"Tick":time.Tick,
		"ParseDuration":time.ParseDuration,
		"Since":time.Since,
		"Until":time.Until,
		"Location":func(inf interface{}) *time.Location {if inf == nil {return new(time.Location)};switch v := inf.(type){case *time.Location:return v;case time.Location:return &v;default:if t, ok := inf.(*time.Location); ok {return t}else if t, ok := inf.(time.Location); ok {return &t};return (*time.Location)(nil)}},
		"Local":time.Local,
		"UTC":time.UTC,
		"FixedZone":time.FixedZone,
		"LoadLocation":time.LoadLocation,
		"LoadLocationFromTZData":time.LoadLocationFromTZData,
		"Month":func(Month int) time.Month {return time.Month(Month)},
		"Ticker":func(inf interface{}) *time.Ticker {if inf == nil {return new(time.Ticker)};switch v := inf.(type){case *time.Ticker:return v;case time.Ticker:return &v;default:if t, ok := inf.(*time.Ticker); ok {return t}else if t, ok := inf.(time.Ticker); ok {return &t};return (*time.Ticker)(nil)}},
		"NewTicker":time.NewTicker,
		"Time":func(inf interface{}) *time.Time {if inf == nil {return new(time.Time)};switch v := inf.(type){case *time.Time:return v;case time.Time:return &v;default:if t, ok := inf.(*time.Time); ok {return t}else if t, ok := inf.(time.Time); ok {return &t};return (*time.Time)(nil)}},
		"Date":time.Date,
		"Now":time.Now,
		"Parse":time.Parse,
		"ParseInLocation":time.ParseInLocation,
		"Unix":time.Unix,
		"Timer":func(inf interface{}) *time.Timer {if inf == nil {return new(time.Timer)};switch v := inf.(type){case *time.Timer:return v;case time.Timer:return &v;default:if t, ok := inf.(*time.Timer); ok {return t}else if t, ok := inf.(time.Timer); ok {return &t};return (*time.Timer)(nil)}},
		"AfterFunc":time.AfterFunc,
		"NewTimer":time.NewTimer,
		"Weekday":func(Weekday int) time.Weekday {return time.Weekday(Weekday)},
    },
    "net":{
		"DefaultResolver":net.DefaultResolver,
		"InterfaceAddrs":net.InterfaceAddrs,
		"Interfaces":net.Interfaces,
		"JoinHostPort":net.JoinHostPort,
		"LookupAddr":net.LookupAddr,
		"LookupCNAME":net.LookupCNAME,
		"LookupHost":net.LookupHost,
		"LookupIP":net.LookupIP,
		"LookupMX":net.LookupMX,
		"LookupNS":net.LookupNS,
		"LookupPort":net.LookupPort,
		"LookupSRV":net.LookupSRV,
		"LookupTXT":net.LookupTXT,
		"SplitHostPort":net.SplitHostPort,
		"Buffers":func(Buffers [][]byte) net.Buffers {return Buffers},
		"Dial":net.Dial,
		"DialTimeout":net.DialTimeout,
		"Dialer":func(inf interface{}) *net.Dialer {if inf == nil {return new(net.Dialer)};switch v := inf.(type){case *net.Dialer:return v;case net.Dialer:return &v;default:if t, ok := inf.(*net.Dialer); ok {return t}else if t, ok := inf.(net.Dialer); ok {return &t};return (*net.Dialer)(nil)}},
		"Flags":func(Flags uint) net.Flags {return net.Flags(Flags)},
		"HardwareAddr":func(HardwareAddr []byte) net.HardwareAddr {return HardwareAddr},
		"ParseMAC":net.ParseMAC,
		"IP":func(IP []byte) net.IP {return IP},
		"IPv4":net.IPv4,
		"ParseCIDR":net.ParseCIDR,
		"ParseIP":net.ParseIP,
		"IPAddr":func(inf interface{}) *net.IPAddr {if inf == nil {return new(net.IPAddr)};switch v := inf.(type){case *net.IPAddr:return v;case net.IPAddr:return &v;default:if t, ok := inf.(*net.IPAddr); ok {return t}else if t, ok := inf.(net.IPAddr); ok {return &t};return (*net.IPAddr)(nil)}},
		"ResolveIPAddr":net.ResolveIPAddr,
		"IPConn":func(inf interface{}) *net.IPConn {if inf == nil {return new(net.IPConn)};switch v := inf.(type){case *net.IPConn:return v;case net.IPConn:return &v;default:if t, ok := inf.(*net.IPConn); ok {return t}else if t, ok := inf.(net.IPConn); ok {return &t};return (*net.IPConn)(nil)}},
		"DialIP":net.DialIP,
		"IPMask":func(IPMask []byte) net.IPMask {return IPMask},
		"CIDRMask":net.CIDRMask,
		"IPv4Mask":net.IPv4Mask,
		"IPNet":func(inf interface{}) *net.IPNet {if inf == nil {return new(net.IPNet)};switch v := inf.(type){case *net.IPNet:return v;case net.IPNet:return &v;default:if t, ok := inf.(*net.IPNet); ok {return t}else if t, ok := inf.(net.IPNet); ok {return &t};return (*net.IPNet)(nil)}},
		"Interface":func(inf interface{}) *net.Interface {if inf == nil {return new(net.Interface)};switch v := inf.(type){case *net.Interface:return v;case net.Interface:return &v;default:if t, ok := inf.(*net.Interface); ok {return t}else if t, ok := inf.(net.Interface); ok {return &t};return (*net.Interface)(nil)}},
		"InterfaceByIndex":net.InterfaceByIndex,
		"InterfaceByName":net.InterfaceByName,
		"MX":func(inf interface{}) *net.MX {if inf == nil {return new(net.MX)};switch v := inf.(type){case *net.MX:return v;case net.MX:return &v;default:if t, ok := inf.(*net.MX); ok {return t}else if t, ok := inf.(net.MX); ok {return &t};return (*net.MX)(nil)}},
		"NS":func(inf interface{}) *net.NS {if inf == nil {return new(net.NS)};switch v := inf.(type){case *net.NS:return v;case net.NS:return &v;default:if t, ok := inf.(*net.NS); ok {return t}else if t, ok := inf.(net.NS); ok {return &t};return (*net.NS)(nil)}},
		"Resolver":func(inf interface{}) *net.Resolver {if inf == nil {return new(net.Resolver)};switch v := inf.(type){case *net.Resolver:return v;case net.Resolver:return &v;default:if t, ok := inf.(*net.Resolver); ok {return t}else if t, ok := inf.(net.Resolver); ok {return &t};return (*net.Resolver)(nil)}},
		"SRV":func(inf interface{}) *net.SRV {if inf == nil {return new(net.SRV)};switch v := inf.(type){case *net.SRV:return v;case net.SRV:return &v;default:if t, ok := inf.(*net.SRV); ok {return t}else if t, ok := inf.(net.SRV); ok {return &t};return (*net.SRV)(nil)}},
		"TCPAddr":func(inf interface{}) *net.TCPAddr {if inf == nil {return new(net.TCPAddr)};switch v := inf.(type){case *net.TCPAddr:return v;case net.TCPAddr:return &v;default:if t, ok := inf.(*net.TCPAddr); ok {return t}else if t, ok := inf.(net.TCPAddr); ok {return &t};return (*net.TCPAddr)(nil)}},
		"ResolveTCPAddr":net.ResolveTCPAddr,
		"TCPConn":func(inf interface{}) *net.TCPConn {if inf == nil {return new(net.TCPConn)};switch v := inf.(type){case *net.TCPConn:return v;case net.TCPConn:return &v;default:if t, ok := inf.(*net.TCPConn); ok {return t}else if t, ok := inf.(net.TCPConn); ok {return &t};return (*net.TCPConn)(nil)}},
		"DialTCP":net.DialTCP,
		"UDPAddr":func(inf interface{}) *net.UDPAddr {if inf == nil {return new(net.UDPAddr)};switch v := inf.(type){case *net.UDPAddr:return v;case net.UDPAddr:return &v;default:if t, ok := inf.(*net.UDPAddr); ok {return t}else if t, ok := inf.(net.UDPAddr); ok {return &t};return (*net.UDPAddr)(nil)}},
		"ResolveUDPAddr":net.ResolveUDPAddr,
		"UDPConn":func(inf interface{}) *net.UDPConn {if inf == nil {return new(net.UDPConn)};switch v := inf.(type){case *net.UDPConn:return v;case net.UDPConn:return &v;default:if t, ok := inf.(*net.UDPConn); ok {return t}else if t, ok := inf.(net.UDPConn); ok {return &t};return (*net.UDPConn)(nil)}},
		"DialUDP":net.DialUDP,
		"ListenMulticastUDP":net.ListenMulticastUDP,
		"ListenUDP":net.ListenUDP,
    },
	"net/http":{
		"LocalAddrContextKey":http.LocalAddrContextKey,
		"ServerContextKey":http.ServerContextKey,
		"NoBody":http.NoBody,
		"DefaultClient":http.DefaultClient,
		"DefaultTransport":http.DefaultTransport,
		"Client":func(inf interface{}) *http.Client {if inf == nil {return new(http.Client)};switch v := inf.(type){case *http.Client:return v;case http.Client:return &v;default:if t, ok := inf.(*http.Client); ok {return t}else if t, ok := inf.(http.Client); ok {return &t};return (*http.Client)(nil)}},
		"ConnState":func(ConnState int) http.ConnState {return http.ConnState(ConnState)},
		"Cookie":func(inf interface{}) *http.Cookie {if inf == nil {return new(http.Cookie)};switch v := inf.(type){case *http.Cookie:return v;case http.Cookie:return &v;default:if t, ok := inf.(*http.Cookie); ok {return t}else if t, ok := inf.(http.Cookie); ok {return &t};return (*http.Cookie)(nil)}},
		"SameSite":func(SameSite int) http.SameSite {return http.SameSite(SameSite)},
		"Header":func(inf interface{}) *http.Header {if inf == nil {return new(http.Header)};switch v := inf.(type){case *http.Header:return v;case http.Header:return &v;default:if t, ok := inf.(*http.Header); ok {return t}else if t, ok := inf.(http.Header); ok {return &t};return (*http.Header)(nil)}},
		"PushOptions":func(inf interface{}) *http.PushOptions {if inf == nil {return new(http.PushOptions)};switch v := inf.(type){case *http.PushOptions:return v;case http.PushOptions:return &v;default:if t, ok := inf.(*http.PushOptions); ok {return t}else if t, ok := inf.(http.PushOptions); ok {return &t};return (*http.PushOptions)(nil)}},
		"Request":func(inf interface{}) *http.Request {if inf == nil {return new(http.Request)};switch v := inf.(type){case *http.Request:return v;case http.Request:return &v;default:if t, ok := inf.(*http.Request); ok {return t}else if t, ok := inf.(http.Request); ok {return &t};return (*http.Request)(nil)}},
		"NewRequest":http.NewRequest,
		"ReadRequest":http.ReadRequest,
		"Response":func(inf interface{}) *http.Response {if inf == nil {return new(http.Response)};switch v := inf.(type){case *http.Response:return v;case http.Response:return &v;default:if t, ok := inf.(*http.Response); ok {return t}else if t, ok := inf.(http.Response); ok {return &t};return (*http.Response)(nil)}},
		"Get":http.Get,
		"Head":http.Head,
		"Post":http.Post,
		"PostForm":http.PostForm,
		"ReadResponse":http.ReadResponse,
		"Transport":func(inf interface{}) *http.Transport {if inf == nil {return new(http.Transport)};switch v := inf.(type){case *http.Transport:return v;case http.Transport:return &v;default:if t, ok := inf.(*http.Transport); ok {return t}else if t, ok := inf.(http.Transport); ok {return &t};return (*http.Transport)(nil)}},
	},
	"crypto":{
		"RegisterHash":crypto.RegisterHash,
		"Hash":func(Hash int) crypto.Hash {return crypto.Hash(Hash)},
	},
	"crypto/aes":{
		"NewCipher":aes.NewCipher,
	},
	"crypto/des":{
		"NewCipher":des.NewCipher,
		"NewTripleDESCipher":des.NewTripleDESCipher,
	},
	"crypto/dsa":{
		"GenerateKey":dsa.GenerateKey,
		"GenerateParameters":dsa.GenerateParameters,
		"Sign":dsa.Sign,
		"Verify":dsa.Verify,
		"ParameterSizes":func(ParameterSizes int) dsa.ParameterSizes {return dsa.ParameterSizes(ParameterSizes)},
		"Parameters":func(inf interface{}) *dsa.Parameters {if inf == nil {return new(dsa.Parameters)};switch v := inf.(type){case *dsa.Parameters:return v;case dsa.Parameters:return &v;default:if t, ok := inf.(*dsa.Parameters); ok {return t}else if t, ok := inf.(dsa.Parameters); ok {return &t};return (*dsa.Parameters)(nil)}},
		"PrivateKey":func(inf interface{}) *dsa.PrivateKey {if inf == nil {return new(dsa.PrivateKey)};switch v := inf.(type){case *dsa.PrivateKey:return v;case dsa.PrivateKey:return &v;default:if t, ok := inf.(*dsa.PrivateKey); ok {return t}else if t, ok := inf.(dsa.PrivateKey); ok {return &t};return (*dsa.PrivateKey)(nil)}},
		"PublicKey":func(inf interface{}) *dsa.PublicKey {if inf == nil {return new(dsa.PublicKey)};switch v := inf.(type){case *dsa.PublicKey:return v;case dsa.PublicKey:return &v;default:if t, ok := inf.(*dsa.PublicKey); ok {return t}else if t, ok := inf.(dsa.PublicKey); ok {return &t};return (*dsa.PublicKey)(nil)}},
	},
	"crypto/rsa":{
		"DecryptOAEP":rsa.DecryptOAEP,
		"DecryptPKCS1v15":rsa.DecryptPKCS1v15,
		"DecryptPKCS1v15SessionKey":rsa.DecryptPKCS1v15SessionKey,
		"EncryptOAEP":rsa.EncryptOAEP,
		"EncryptPKCS1v15":rsa.EncryptPKCS1v15,
		"SignPKCS1v15":rsa.SignPKCS1v15,
		"SignPSS":rsa.SignPSS,
		"VerifyPKCS1v15":rsa.VerifyPKCS1v15,
		"VerifyPSS":rsa.VerifyPSS,
		"CRTValue":func(inf interface{}) *rsa.CRTValue {if inf == nil {return new(rsa.CRTValue)};switch v := inf.(type){case *rsa.CRTValue:return v;case rsa.CRTValue:return &v;default:if t, ok := inf.(*rsa.CRTValue); ok {return t}else if t, ok := inf.(rsa.CRTValue); ok {return &t};return (*rsa.CRTValue)(nil)}},
		"OAEPOptions":func(inf interface{}) *rsa.OAEPOptions {if inf == nil {return new(rsa.OAEPOptions)};switch v := inf.(type){case *rsa.OAEPOptions:return v;case rsa.OAEPOptions:return &v;default:if t, ok := inf.(*rsa.OAEPOptions); ok {return t}else if t, ok := inf.(rsa.OAEPOptions); ok {return &t};return (*rsa.OAEPOptions)(nil)}},
		"PKCS1v15DecryptOptions":func(inf interface{}) *rsa.PKCS1v15DecryptOptions {if inf == nil {return new(rsa.PKCS1v15DecryptOptions)};switch v := inf.(type){case *rsa.PKCS1v15DecryptOptions:return v;case rsa.PKCS1v15DecryptOptions:return &v;default:if t, ok := inf.(*rsa.PKCS1v15DecryptOptions); ok {return t}else if t, ok := inf.(rsa.PKCS1v15DecryptOptions); ok {return &t};return (*rsa.PKCS1v15DecryptOptions)(nil)}},
		"PSSOptions":func(inf interface{}) *rsa.PSSOptions {if inf == nil {return new(rsa.PSSOptions)};switch v := inf.(type){case *rsa.PSSOptions:return v;case rsa.PSSOptions:return &v;default:if t, ok := inf.(*rsa.PSSOptions); ok {return t}else if t, ok := inf.(rsa.PSSOptions); ok {return &t};return (*rsa.PSSOptions)(nil)}},
		"PrecomputedValues":func(inf interface{}) *rsa.PrecomputedValues {if inf == nil {return new(rsa.PrecomputedValues)};switch v := inf.(type){case *rsa.PrecomputedValues:return v;case rsa.PrecomputedValues:return &v;default:if t, ok := inf.(*rsa.PrecomputedValues); ok {return t}else if t, ok := inf.(rsa.PrecomputedValues); ok {return &t};return (*rsa.PrecomputedValues)(nil)}},
		"PrivateKey":func(inf interface{}) *rsa.PrivateKey {if inf == nil {return new(rsa.PrivateKey)};switch v := inf.(type){case *rsa.PrivateKey:return v;case rsa.PrivateKey:return &v;default:if t, ok := inf.(*rsa.PrivateKey); ok {return t}else if t, ok := inf.(rsa.PrivateKey); ok {return &t};return (*rsa.PrivateKey)(nil)}},
		"GenerateKey":rsa.GenerateKey,
		"GenerateMultiPrimeKey":rsa.GenerateMultiPrimeKey,
		"PublicKey":func(inf interface{}) *rsa.PublicKey {if inf == nil {return new(rsa.PublicKey)};switch v := inf.(type){case *rsa.PublicKey:return v;case rsa.PublicKey:return &v;default:if t, ok := inf.(*rsa.PublicKey); ok {return t}else if t, ok := inf.(rsa.PublicKey); ok {return &t};return (*rsa.PublicKey)(nil)}},
	},
	"crypto/ecdsa":{
		"Sign":ecdsa.Sign,
		"Verify":ecdsa.Verify,
		"GenerateKey":ecdsa.GenerateKey,
		"PrivateKey":func(inf interface{}) *ecdsa.PrivateKey {if inf == nil {return new(ecdsa.PrivateKey)};switch v := inf.(type){case *ecdsa.PrivateKey:return v;case ecdsa.PrivateKey:return &v;default:if t, ok := inf.(*ecdsa.PrivateKey); ok {return t}else if t, ok := inf.(ecdsa.PrivateKey); ok {return &t};return (*ecdsa.PrivateKey)(nil)}},
		"PublicKey":func(inf interface{}) *ecdsa.PublicKey {if inf == nil {return new(ecdsa.PublicKey)};switch v := inf.(type){case *ecdsa.PublicKey:return v;case ecdsa.PublicKey:return &v;default:if t, ok := inf.(*ecdsa.PublicKey); ok {return t}else if t, ok := inf.(ecdsa.PublicKey); ok {return &t};return (*ecdsa.PublicKey)(nil)}},
	},
	"crypto/elliptic":{
		"GenerateKey":elliptic.GenerateKey,
		"Marshal":elliptic.Marshal,
		"Unmarshal":elliptic.Unmarshal,
		"P224":elliptic.P224,
		"P256":elliptic.P256,
		"P384":elliptic.P384,
		"P521":elliptic.P521,
		"CurveParams":func(inf interface{}) *elliptic.CurveParams {if inf == nil {return new(elliptic.CurveParams)};switch v := inf.(type){case *elliptic.CurveParams:return v;case elliptic.CurveParams:return &v;default:if t, ok := inf.(*elliptic.CurveParams); ok {return t}else if t, ok := inf.(elliptic.CurveParams); ok {return &t};return (*elliptic.CurveParams)(nil)}},
	},
	"crypto/hmac":{
		"Equal":hmac.Equal,
		"New":hmac.New,
	},
	"crypto/rand":{
		"Reader":rand.Reader,
		"Int":rand.Int,
		"Prime":rand.Prime,
		"Read":rand.Read,
	},
	"crypto/cipher":{
		"NewGCMWithTagSize":cipher.NewGCMWithTagSize,
		"NewGCM":cipher.NewGCM,
		"NewGCMWithNonceSize":cipher.NewGCMWithNonceSize,
		"NewCBCDecrypter":cipher.NewCBCDecrypter,
		"NewCBCEncrypter":cipher.NewCBCEncrypter,
		"NewCFBDecrypter":cipher.NewCFBDecrypter,
		"NewCFBEncrypter":cipher.NewCFBEncrypter,
		"NewCTR":cipher.NewCTR,
		"NewOFB":cipher.NewOFB,
		"StreamReader":func(inf interface{}) *cipher.StreamReader {if inf == nil {return new(cipher.StreamReader)};switch v := inf.(type){case *cipher.StreamReader:return v;case cipher.StreamReader:return &v;default:if t, ok := inf.(*cipher.StreamReader); ok {return t}else if t, ok := inf.(cipher.StreamReader); ok {return &t};return (*cipher.StreamReader)(nil)}},
		"StreamWriter":func(inf interface{}) *cipher.StreamWriter {if inf == nil {return new(cipher.StreamWriter)};switch v := inf.(type){case *cipher.StreamWriter:return v;case cipher.StreamWriter:return &v;default:if t, ok := inf.(*cipher.StreamWriter); ok {return t}else if t, ok := inf.(cipher.StreamWriter); ok {return &t};return (*cipher.StreamWriter)(nil)}},
	},
	"crypto/tls":{
		"Certificate":func(inf interface{}) *tls.Certificate {if inf == nil {return new(tls.Certificate)};switch v := inf.(type){case *tls.Certificate:return v;case tls.Certificate:return &v;default:if t, ok := inf.(*tls.Certificate); ok {return t}else if t, ok := inf.(tls.Certificate); ok {return &t};return (*tls.Certificate)(nil)}},
		"LoadX509KeyPair":tls.LoadX509KeyPair,
		"X509KeyPair":tls.X509KeyPair,
		"CertificateRequestInfo":func(inf interface{}) *tls.CertificateRequestInfo {if inf == nil {return new(tls.CertificateRequestInfo)};switch v := inf.(type){case *tls.CertificateRequestInfo:return v;case tls.CertificateRequestInfo:return &v;default:if t, ok := inf.(*tls.CertificateRequestInfo); ok {return t}else if t, ok := inf.(tls.CertificateRequestInfo); ok {return &t};return (*tls.CertificateRequestInfo)(nil)}},
		"ClientAuthType":func(ClientAuthType int) tls.ClientAuthType {return tls.ClientAuthType(ClientAuthType)},
		"ClientHelloInfo":func(inf interface{}) *tls.ClientHelloInfo {if inf == nil {return new(tls.ClientHelloInfo)};switch v := inf.(type){case *tls.ClientHelloInfo:return v;case tls.ClientHelloInfo:return &v;default:if t, ok := inf.(*tls.ClientHelloInfo); ok {return t}else if t, ok := inf.(tls.ClientHelloInfo); ok {return &t};return (*tls.ClientHelloInfo)(nil)}},
		"NewLRUClientSessionCache":tls.NewLRUClientSessionCache,
		"ClientSessionState":func(inf interface{}) *tls.ClientSessionState {if inf == nil {return new(tls.ClientSessionState)};switch v := inf.(type){case *tls.ClientSessionState:return v;case tls.ClientSessionState:return &v;default:if t, ok := inf.(*tls.ClientSessionState); ok {return t}else if t, ok := inf.(tls.ClientSessionState); ok {return &t};return (*tls.ClientSessionState)(nil)}},
		"Config":func(inf interface{}) *tls.Config {if inf == nil {return new(tls.Config)};switch v := inf.(type){case *tls.Config:return v;case tls.Config:return &v;default:if t, ok := inf.(*tls.Config); ok {return t}else if t, ok := inf.(tls.Config); ok {return &t};return (*tls.Config)(nil)}},
		"Conn":func(inf interface{}) *tls.Conn {if inf == nil {return new(tls.Conn)};switch v := inf.(type){case *tls.Conn:return v;case tls.Conn:return &v;default:if t, ok := inf.(*tls.Conn); ok {return t}else if t, ok := inf.(tls.Conn); ok {return &t};return (*tls.Conn)(nil)}},
		"Client":tls.Client,
		"Dial":tls.Dial,
		"DialWithDialer":tls.DialWithDialer,
		"ConnectionState":func(inf interface{}) *tls.ConnectionState {if inf == nil {return new(tls.ConnectionState)};switch v := inf.(type){case *tls.ConnectionState:return v;case tls.ConnectionState:return &v;default:if t, ok := inf.(*tls.ConnectionState); ok {return t}else if t, ok := inf.(tls.ConnectionState); ok {return &t};return (*tls.ConnectionState)(nil)}},
		"CurveID":func(CurveID uint16) tls.CurveID {return tls.CurveID(CurveID)},
		"RenegotiationSupport":func(RenegotiationSupport int) tls.RenegotiationSupport {return tls.RenegotiationSupport(RenegotiationSupport)},
		"SignatureScheme":func(SignatureScheme uint16) tls.SignatureScheme {return tls.SignatureScheme(SignatureScheme)},
   	},
   	"crypto/x509":{
		"CreateCertificate":x509.CreateCertificate,
		"CreateCertificateRequest":x509.CreateCertificateRequest,
		"DecryptPEMBlock":x509.DecryptPEMBlock,
		"EncryptPEMBlock":x509.EncryptPEMBlock,
		"IsEncryptedPEMBlock":x509.IsEncryptedPEMBlock,
		"MarshalECPrivateKey":x509.MarshalECPrivateKey,
		"MarshalPKCS1PublicKey":x509.MarshalPKCS1PublicKey,
		"MarshalPKCS1PrivateKey":x509.MarshalPKCS1PrivateKey,
		"MarshalPKIXPublicKey":x509.MarshalPKIXPublicKey,
		"MarshalPKCS8PrivateKey":x509.MarshalPKCS8PrivateKey,
		"ParseCRL":x509.ParseCRL,
		"ParseCertificates":x509.ParseCertificates,
		"ParseDERCRL":x509.ParseDERCRL,
		"ParseECPrivateKey":x509.ParseECPrivateKey,
		"ParsePKCS1PublicKey":x509.ParsePKCS1PublicKey,
		"ParsePKCS1PrivateKey":x509.ParsePKCS1PrivateKey,
		"ParsePKCS8PrivateKey":x509.ParsePKCS8PrivateKey,
		"ParsePKIXPublicKey":x509.ParsePKIXPublicKey,
		"CertPool":func(inf interface{}) *x509.CertPool {if inf == nil {return new(x509.CertPool)};switch v := inf.(type){case *x509.CertPool:return v;case x509.CertPool:return &v;default:if t, ok := inf.(*x509.CertPool); ok {return t}else if t, ok := inf.(x509.CertPool); ok {return &t};return (*x509.CertPool)(nil)}},
		"NewCertPool":x509.NewCertPool,
		"SystemCertPool":x509.SystemCertPool,
		"Certificate":func(inf interface{}) *x509.Certificate {if inf == nil {return new(x509.Certificate)};switch v := inf.(type){case *x509.Certificate:return v;case x509.Certificate:return &v;default:if t, ok := inf.(*x509.Certificate); ok {return t}else if t, ok := inf.(x509.Certificate); ok {return &t};return (*x509.Certificate)(nil)}},
		"ParseCertificate":x509.ParseCertificate,
		"CertificateRequest":func(inf interface{}) *x509.CertificateRequest {if inf == nil {return new(x509.CertificateRequest)};switch v := inf.(type){case *x509.CertificateRequest:return v;case x509.CertificateRequest:return &v;default:if t, ok := inf.(*x509.CertificateRequest); ok {return t}else if t, ok := inf.(x509.CertificateRequest); ok {return &t};return (*x509.CertificateRequest)(nil)}},
		"ParseCertificateRequest":x509.ParseCertificateRequest,
		"KeyUsage":func(KeyUsage int) x509.KeyUsage {return x509.KeyUsage(KeyUsage)},
		"PEMCipher":func(PEMCipher int) x509.PEMCipher {return x509.PEMCipher(PEMCipher)},
		"PublicKeyAlgorithm":func(PublicKeyAlgorithm int) x509.PublicKeyAlgorithm {return x509.PublicKeyAlgorithm(PublicKeyAlgorithm)},
		"SignatureAlgorithm":func(SignatureAlgorithm int) x509.SignatureAlgorithm {return x509.SignatureAlgorithm(SignatureAlgorithm)},
		"VerifyOptions":func(inf interface{}) *x509.VerifyOptions {if inf == nil {return new(x509.VerifyOptions)};switch v := inf.(type){case *x509.VerifyOptions:return v;case x509.VerifyOptions:return &v;default:if t, ok := inf.(*x509.VerifyOptions); ok {return t}else if t, ok := inf.(x509.VerifyOptions); ok {return &t};return (*x509.VerifyOptions)(nil)}},
	},
	"crypto/x509/pkix":{
		"AlgorithmIdentifier":func(inf interface{}) *pkix.AlgorithmIdentifier {if inf == nil {return new(pkix.AlgorithmIdentifier)};switch v := inf.(type){case *pkix.AlgorithmIdentifier:return v;case pkix.AlgorithmIdentifier:return &v;default:if t, ok := inf.(*pkix.AlgorithmIdentifier); ok {return t}else if t, ok := inf.(pkix.AlgorithmIdentifier); ok {return &t};return (*pkix.AlgorithmIdentifier)(nil)}},
		"AttributeTypeAndValue":func(inf interface{}) *pkix.AttributeTypeAndValue {if inf == nil {return new(pkix.AttributeTypeAndValue)};switch v := inf.(type){case *pkix.AttributeTypeAndValue:return v;case pkix.AttributeTypeAndValue:return &v;default:if t, ok := inf.(*pkix.AttributeTypeAndValue); ok {return t}else if t, ok := inf.(pkix.AttributeTypeAndValue); ok {return &t};return (*pkix.AttributeTypeAndValue)(nil)}},
		"AttributeTypeAndValueSET":func(inf interface{}) *pkix.AttributeTypeAndValueSET {if inf == nil {return new(pkix.AttributeTypeAndValueSET)};switch v := inf.(type){case *pkix.AttributeTypeAndValueSET:return v;case pkix.AttributeTypeAndValueSET:return &v;default:if t, ok := inf.(*pkix.AttributeTypeAndValueSET); ok {return t}else if t, ok := inf.(pkix.AttributeTypeAndValueSET); ok {return &t};return (*pkix.AttributeTypeAndValueSET)(nil)}},
		"CertificateList":func(inf interface{}) *pkix.CertificateList {if inf == nil {return new(pkix.CertificateList)};switch v := inf.(type){case *pkix.CertificateList:return v;case pkix.CertificateList:return &v;default:if t, ok := inf.(*pkix.CertificateList); ok {return t}else if t, ok := inf.(pkix.CertificateList); ok {return &t};return (*pkix.CertificateList)(nil)}},
		"Extension":func(inf interface{}) *pkix.Extension {if inf == nil {return new(pkix.Extension)};switch v := inf.(type){case *pkix.Extension:return v;case pkix.Extension:return &v;default:if t, ok := inf.(*pkix.Extension); ok {return t}else if t, ok := inf.(pkix.Extension); ok {return &t};return (*pkix.Extension)(nil)}},
		"Name":func(inf interface{}) *pkix.Name {if inf == nil {return new(pkix.Name)};switch v := inf.(type){case *pkix.Name:return v;case pkix.Name:return &v;default:if t, ok := inf.(*pkix.Name); ok {return t}else if t, ok := inf.(pkix.Name); ok {return &t};return (*pkix.Name)(nil)}},
		"RDNSequence":func(RDNSequence []pkix.RelativeDistinguishedNameSET) pkix.RDNSequence {return RDNSequence},
		"RelativeDistinguishedNameSET":func(RelativeDistinguishedNameSET []pkix.AttributeTypeAndValue) pkix.RelativeDistinguishedNameSET {return RelativeDistinguishedNameSET},
		"RevokedCertificate":func(inf interface{}) *pkix.RevokedCertificate {if inf == nil {return new(pkix.RevokedCertificate)};switch v := inf.(type){case *pkix.RevokedCertificate:return v;case pkix.RevokedCertificate:return &v;default:if t, ok := inf.(*pkix.RevokedCertificate); ok {return t}else if t, ok := inf.(pkix.RevokedCertificate); ok {return &t};return (*pkix.RevokedCertificate)(nil)}},
		"TBSCertificateList":func(inf interface{}) *pkix.TBSCertificateList {if inf == nil {return new(pkix.TBSCertificateList)};switch v := inf.(type){case *pkix.TBSCertificateList:return v;case pkix.TBSCertificateList:return &v;default:if t, ok := inf.(*pkix.TBSCertificateList); ok {return t}else if t, ok := inf.(pkix.TBSCertificateList); ok {return &t};return (*pkix.TBSCertificateList)(nil)}},
	},
	"crypto/sha1":{
		"New":sha1.New,
		"Sum":sha1.Sum,
	},
	"crypto/sha256":{
		"New":sha256.New,
		"New224":sha256.New224,
		"Sum224":sha256.Sum224,
		"Sum256":sha256.Sum256,
	},
	"crypto/sha512":{
		"New":sha512.New,
		"New384":sha512.New384,
		"New512_224":sha512.New512_224,
		"New512_256":sha512.New512_256,
		"Sum384":sha512.Sum384,
		"Sum512":sha512.Sum512,
		"Sum512_224":sha512.Sum512_224,
		"Sum512_256":sha512.Sum512_256,
	},
	"encoding/asn1":{
		"MarshalWithParams":asn1.MarshalWithParams,
		"Marshal":asn1.Marshal,
		"Unmarshal":asn1.Unmarshal,
		"UnmarshalWithParams":asn1.UnmarshalWithParams,
		"BitString":func(inf interface{}) *asn1.BitString {if inf == nil {return new(asn1.BitString)};switch v := inf.(type){case *asn1.BitString:return v;case asn1.BitString:return &v;default:if t, ok := inf.(*asn1.BitString); ok {return t}else if t, ok := inf.(asn1.BitString); ok {return &t};return (*asn1.BitString)(nil)}},
		"Flag":func(Flag bool) asn1.Flag {return asn1.Flag(Flag)},
		"ObjectIdentifier":func(ObjectIdentifier []int) asn1.ObjectIdentifier {return ObjectIdentifier},
		"RawContent":func(RawContent []byte) asn1.RawContent {return RawContent},
		"RawValue":func(inf interface{}) *asn1.RawValue {if inf == nil {return new(asn1.RawValue)};switch v := inf.(type){case *asn1.RawValue:return v;case asn1.RawValue:return &v;default:if t, ok := inf.(*asn1.RawValue); ok {return t}else if t, ok := inf.(asn1.RawValue); ok {return &t};return (*asn1.RawValue)(nil)}},
	},
	"math/big":{
		"Jacobi":big.Jacobi,
		"Accuracy":func(Accuracy int8) big.Accuracy {return big.Accuracy(Accuracy)},
		"Float":func(inf interface{}) *big.Float {if inf == nil {return new(big.Float)};switch v := inf.(type){case *big.Float:return v;case big.Float:return &v;default:if t, ok := inf.(*big.Float); ok {return t}else if t, ok := inf.(big.Float); ok {return &t};return (*big.Float)(nil)}},
		"NewFloat":big.NewFloat,
		"ParseFloat":big.ParseFloat,
		"Int":func(inf interface{}) *big.Int {if inf == nil {return new(big.Int)};switch v := inf.(type){case *big.Int:return v;case big.Int:return &v;default:if t, ok := inf.(*big.Int); ok {return t}else if t, ok := inf.(big.Int); ok {return &t};return (*big.Int)(nil)}},
		"NewInt":big.NewInt,
		"Rat":func(inf interface{}) *big.Rat {if inf == nil {return new(big.Rat)};switch v := inf.(type){case *big.Rat:return v;case big.Rat:return &v;default:if t, ok := inf.(*big.Rat); ok {return t}else if t, ok := inf.(big.Rat); ok {return &t};return (*big.Rat)(nil)}},
		"NewRat":big.NewRat,
		"RoundingMode":func(RoundingMode byte) big.RoundingMode {return big.RoundingMode(RoundingMode)},
		"Word":func(Word uint) big.Word {return big.Word(Word)},
	},
	"bufio":{
		"ScanBytes":bufio.ScanBytes,
		"ScanLines":bufio.ScanLines,
		"ScanRunes":bufio.ScanRunes,
		"ScanWords":bufio.ScanWords,
		"ReadWriter":func(inf interface{}) *bufio.ReadWriter {if inf == nil {return new(bufio.ReadWriter)};switch v := inf.(type){case *bufio.ReadWriter:return v;case bufio.ReadWriter:return &v;default:if t, ok := inf.(*bufio.ReadWriter); ok {return t}else if t, ok := inf.(bufio.ReadWriter); ok {return &t};return (*bufio.ReadWriter)(nil)}},
		"NewReadWriter":bufio.NewReadWriter,
		"Reader":func(inf interface{}) *bufio.Reader {if inf == nil {return new(bufio.Reader)};switch v := inf.(type){case *bufio.Reader:return v;case bufio.Reader:return &v;default:if t, ok := inf.(*bufio.Reader); ok {return t}else if t, ok := inf.(bufio.Reader); ok {return &t};return (*bufio.Reader)(nil)}},
		"NewReader":bufio.NewReader,
		"NewReaderSize":bufio.NewReaderSize,
		"Writer":func(inf interface{}) *bufio.Writer {if inf == nil {return new(bufio.Writer)};switch v := inf.(type){case *bufio.Writer:return v;case bufio.Writer:return &v;default:if t, ok := inf.(*bufio.Writer); ok {return t}else if t, ok := inf.(bufio.Writer); ok {return &t};return (*bufio.Writer)(nil)}},
		"NewWriter":bufio.NewWriter,
		"NewWriterSize":bufio.NewWriterSize,
		"Scanner":func(inf interface{}) *bufio.Scanner {if inf == nil {return new(bufio.Scanner)};switch v := inf.(type){case *bufio.Scanner:return v;case bufio.Scanner:return &v;default:if t, ok := inf.(*bufio.Scanner); ok {return t}else if t, ok := inf.(bufio.Scanner); ok {return &t};return (*bufio.Scanner)(nil)}},
		"SplitFunc":func(SplitFunc func(data []byte, atEOF bool) (advance int, token []byte, err error)) bufio.SplitFunc {return bufio.SplitFunc(SplitFunc)},
		"NewScanner":bufio.NewScanner,
	},
	"url":{
		"PathEscape":url.PathEscape,
		"PathUnescape":url.PathUnescape,
		"QueryEscape":url.QueryEscape,
		"QueryUnescape":url.QueryUnescape,
		"URL":func(inf interface{}) *url.URL {if inf == nil {return new(url.URL)};switch v := inf.(type){case *url.URL:return v;case url.URL:return &v;default:if t, ok := inf.(*url.URL); ok {return t}else if t, ok := inf.(url.URL); ok {return &t};return (*url.URL)(nil)}},
		"Parse":url.Parse,
		"ParseRequestURI":url.ParseRequestURI,
		"Userinfo":func(inf interface{}) *url.Userinfo {if inf == nil {return new(url.Userinfo)};switch v := inf.(type){case *url.Userinfo:return v;case url.Userinfo:return &v;default:if t, ok := inf.(*url.Userinfo); ok {return t}else if t, ok := inf.(url.Userinfo); ok {return &t};return (*url.Userinfo)(nil)}},
		"User":url.User,
		"UserPassword":url.UserPassword,
		"Values":func(Values map[string][]string) url.Values {return Values},
		"ParseQuery":url.ParseQuery,
	},
    "strings":{
    	"ReplaceAll":strings.ReplaceAll,
    	"Compare":strings.Compare,
        "Contains":strings.Contains,
        "ContainsAny":strings.ContainsAny,
        "ContainsRune":strings.ContainsRune,
        "Count":strings.Count,
        "EqualFold":strings.EqualFold,
        "Fields":strings.Fields,
        "FieldsFunc":strings.FieldsFunc,
        "HasPrefix":strings.HasPrefix,
        "HasSuffix":strings.HasSuffix,
        "Index":strings.Index,
        "IndexAny":strings.IndexAny,
        "IndexByte":strings.IndexByte,
        "IndexFunc":strings.IndexFunc,
        "IndexRune":strings.IndexRune,
        "LastIndex":strings.LastIndex,
        "LastIndexAny":strings.LastIndexAny,
        "LastIndexByte":strings.LastIndexByte,
        "LastIndexFunc":strings.LastIndexFunc,
        "Map":strings.Map,
        "Repeat":strings.Repeat,
        "Replace":strings.Replace,
        "Join":strings.Join,
        "Split":strings.Split,
        "SplitN":strings.SplitN,
        "SplitAfter":strings.SplitAfter,
        "SplitAfterN":strings.SplitAfterN,
        "Title":strings.Title,
        "ToLower":strings.ToLower,
        "ToLowerSpecial":strings.ToLowerSpecial,
        "ToTitle":strings.ToTitle,
        "ToTitleSpecial":strings.ToTitleSpecial,
        "ToUpper":strings.ToUpper,
        "ToUpperSpecial":strings.ToUpperSpecial,
        "ToValidUTF8":strings.ToValidUTF8,
        "Trim":strings.Trim,
        "TrimFunc":strings.TrimFunc,
        "TrimLeft":strings.TrimLeft,
        "TrimPrefix":strings.TrimPrefix,
        "TrimLeftFunc":strings.TrimLeftFunc,
        "TrimRight":strings.TrimRight,
        "TrimSuffix":strings.TrimSuffix,
        "TrimRightFunc":strings.TrimRightFunc,
        "TrimSpace":strings.TrimSpace,
		"Reader":func(inf interface{}) *strings.Reader {if inf == nil {return new(strings.Reader)};switch v := inf.(type){case *strings.Reader:return v;case strings.Reader:return &v;default:if t, ok := inf.(*strings.Reader); ok {return t}else if t, ok := inf.(strings.Reader); ok {return &t};return (*strings.Reader)(nil)}},
        "NewReader":strings.NewReader,
		"Replacer":func(inf interface{}) *strings.Replacer {if inf == nil {return new(strings.Replacer)};switch v := inf.(type){case *strings.Replacer:return v;case strings.Replacer:return &v;default:if t, ok := inf.(*strings.Replacer); ok {return t}else if t, ok := inf.(strings.Replacer); ok {return &t};return (*strings.Replacer)(nil)}},
        "NewReplacer":strings.NewReplacer,
        "Builder":func(inf interface{}) *strings.Builder {if inf == nil {return new(strings.Builder)};switch v := inf.(type){case *strings.Builder:return v;case strings.Builder:return &v;default:if t, ok := inf.(*strings.Builder); ok {return t}else if t, ok := inf.(strings.Builder); ok {return &t};return (*strings.Builder)(nil)}},
    },
    "bytes":{
    	"ReplaceAll":bytes.ReplaceAll,
        "Compare":bytes.Compare,
        "Contains":bytes.Contains,
        "ContainsAny":bytes.ContainsAny,
        "ContainsRune":bytes.ContainsRune,
        "Count":bytes.Count,
        "Equal":bytes.Equal,
        "EqualFold":bytes.EqualFold,
        "Fields":bytes.Fields,
        "FieldsFunc":bytes.FieldsFunc,
        "HasPrefix":bytes.HasPrefix,
        "HasSuffix":bytes.HasSuffix,
        "Index":bytes.Index,
        "IndexAny":bytes.IndexAny,
        "IndexByte":bytes.IndexByte,
        "IndexFunc":bytes.IndexFunc,
        "IndexRune":bytes.IndexRune,
        "LastIndex":bytes.LastIndex,
        "LastIndexAny":bytes.LastIndexAny,
        "LastIndexByte":bytes.LastIndexByte,
        "LastIndexFunc":bytes.LastIndexFunc,
        "Map":bytes.Map,
        "Repeat":bytes.Repeat,
        "Replace":bytes.Replace,
        "Runes":bytes.Runes,
        "Join":bytes.Join,
        "Split":bytes.Split,
        "SplitN":bytes.SplitN,
        "SplitAfter":bytes.SplitAfter,
        "SplitAfterN":bytes.SplitAfterN,
        "Title":bytes.Title,
        "ToLower":bytes.ToLower,
        "ToLowerSpecial":bytes.ToLowerSpecial,
        "ToTitle":bytes.ToTitle,
        "ToTitleSpecial":bytes.ToTitleSpecial,
        "ToUpper":bytes.ToUpper,
        "ToUpperSpecial":bytes.ToUpperSpecial,
        "ToValidUTF8":bytes.ToValidUTF8,
        "Trim":bytes.Trim,
        "TrimFunc":bytes.TrimFunc,
        "TrimPrefix":bytes.TrimPrefix,
        "TrimLeft":bytes.TrimLeft,
        "TrimLeftFunc":bytes.TrimLeftFunc,
        "TrimSuffix":bytes.TrimSuffix,
        "TrimRight":bytes.TrimRight,
        "TrimRightFunc":bytes.TrimRightFunc,
        "TrimSpace":bytes.TrimSpace,
		"Buffer":func(inf interface{}) *bytes.Buffer {if inf == nil {return new(bytes.Buffer)};switch v := inf.(type){case *bytes.Buffer:return v;case bytes.Buffer:return &v;default:if t, ok := inf.(*bytes.Buffer); ok {return t}else if t, ok := inf.(bytes.Buffer); ok {return &t};return (*bytes.Buffer)(nil)}},
        "NewBuffer":bytes.NewBuffer,
        "NewBufferString":bytes.NewBufferString,
		"Reader":func(inf interface{}) *bytes.Reader {if inf == nil {return new(bytes.Reader)};switch v := inf.(type){case *bytes.Reader:return v;case bytes.Reader:return &v;default:if t, ok := inf.(*bytes.Reader); ok {return t}else if t, ok := inf.(bytes.Reader); ok {return &t};return (*bytes.Reader)(nil)}},
        "NewReader":bytes.NewReader,
    },
    "strconv":{
        "AppendBool":strconv.AppendBool,
        "AppendFloat":strconv.AppendFloat,
        "AppendInt":strconv.AppendInt,
        "AppendUint":strconv.AppendUint,
        "AppendQuote":strconv.AppendQuote,
        "AppendQuoteToASCII":strconv.AppendQuoteToASCII,
        "AppendQuoteRune":strconv.AppendQuoteRune,
        "AppendQuoteRuneToASCII":strconv.AppendQuoteRuneToASCII,
        "AppendQuoteRuneToGraphic":strconv.AppendQuoteRuneToGraphic,
        "AppendQuoteToGraphic":strconv.AppendQuoteToGraphic,
        "Atoi":strconv.Atoi,
        "Itoa":strconv.Itoa,
        "CanBackquote":strconv.CanBackquote,
        "FormatBool":strconv.FormatBool,
        "FormatFloat":strconv.FormatFloat,
        "FormatInt":strconv.FormatInt,
        "FormatUint":strconv.FormatUint,
        "IsGraphic":strconv.IsGraphic,
        "IsPrint":strconv.IsPrint,
        "ParseBool":strconv.ParseBool,
        "ParseFloat":strconv.ParseFloat,
        "ParseInt":strconv.ParseInt,
        "ParseUint":strconv.ParseUint,
        "Quote":strconv.Quote,
        "QuoteToASCII":strconv.QuoteToASCII,
        "QuoteToGraphic":strconv.QuoteToGraphic,
        "QuoteRune":strconv.QuoteRune,
        "QuoteRuneToASCII":strconv.QuoteRuneToASCII,
        "QuoteRuneToGraphic":strconv.QuoteRuneToGraphic,
        "Unquote":strconv.Unquote,
        "UnquoteChar":strconv.UnquoteChar,
    },
    "encoding/json":{
		"Compact":json.Compact,
		"Indent":json.Indent,
		"HTMLEscape":json.HTMLEscape,
		"Marshal":json.Marshal,
		"MarshalIndent":json.MarshalIndent,
		"Unmarshal":json.Unmarshal,
		"NewEncoder":json.NewEncoder,
		"NewDecoder":json.NewDecoder,
		"Valid":json.Valid,
	},
    "regexp":{
        "Match":regexp.Match,
        "MatchReader":regexp.MatchReader,
        "MatchString":regexp.MatchString,
        "QuoteMeta":regexp.QuoteMeta,
        "Compile":regexp.Compile,
        "CompilePOSIX":regexp.CompilePOSIX,
    },
    "unicode":{
    	"In":unicode.In,
        "Is":unicode.Is,
        "IsControl":unicode.IsControl,
        "IsDigit":unicode.IsDigit,
        "IsGraphic":unicode.IsGraphic,
        "IsPrint":unicode.IsPrint,
        "IsLetter":unicode.IsLetter,
        "IsLower":unicode.IsLower,
        "IsTitle":unicode.IsTitle,
        "IsUpper":unicode.IsUpper,
        "IsMark":unicode.IsMark,
        "IsNumber":unicode.IsNumber,
        "IsOneOf":unicode.IsOneOf,
        "IsPunct":unicode.IsPunct,
        "IsSpace":unicode.IsSpace,
        "IsSymbol":unicode.IsSymbol,
        "SimpleFold":unicode.SimpleFold,
        "To":unicode.To,
        "ToLower":unicode.ToLower,
        "ToTitle":unicode.ToTitle,
        "ToUpper":unicode.ToUpper,
    },
    "unicode/utf8":{
        "DecodeLastRune":utf8.DecodeLastRune,
        "DecodeLastRuneInString":utf8.DecodeLastRuneInString,
        "DecodeRune":utf8.DecodeRune,
        "DecodeRuneInString":utf8.DecodeRuneInString,
        "EncodeRune":utf8.EncodeRune,
        "FullRune":utf8.FullRune,
        "FullRuneInString":utf8.FullRuneInString,
        "RuneCount":utf8.RuneCount,
        "RuneCountInString":utf8.RuneCountInString,
        "RuneLen":utf8.RuneLen,
        "RuneStart":utf8.RuneStart,
        "Valid":utf8.Valid,
        "ValidRune":utf8.ValidRune,
        "ValidString":utf8.ValidString,
    },
    "io":{
		"EOF":io.EOF,
		"Copy":io.Copy,
		"CopyBuffer":io.CopyBuffer,
		"CopyN":io.CopyN,
		"ReadAtLeast":io.ReadAtLeast,
		"ReadFull":io.ReadFull,
		"WriteString":io.WriteString,
		"Pipe":io.Pipe,
		"LimitReader":io.LimitReader,
		"MultiReader":io.MultiReader,
		"TeeReader":io.TeeReader,
		"NewSectionReader":io.NewSectionReader,
		"MultiWriter":io.MultiWriter,
    },
    "io/ioutil":{
    	"Discard":ioutil.Discard,
    	"NopCloser":ioutil.NopCloser,
        "ReadAll":ioutil.ReadAll,
        "ReadFile":ioutil.ReadFile,
        "WriteFile":ioutil.WriteFile,
    },
    "os":{
    	"IsTimeout":os.IsTimeout,
    	"IsExist":os.IsExist,
    	"IsNotExist":os.IsNotExist,
    	"IsPermission":os.IsPermission,
    	"Link":os.Link,
    	"Readlink":os.Readlink,
    	"Symlink":os.Symlink,
    	"Mkdir":os.Mkdir,
    	"MkdirAll":os.MkdirAll,
    	"TempDir":os.TempDir,
    	"Remove":os.Remove,
    	"RemoveAll":os.RemoveAll,
    	"Rename":os.Rename,
    	"Create":os.Create,
    	"NewFile":os.NewFile,
    	"Open":os.Open,
    	"OpenFile":os.OpenFile,
    	"Lstat":os.Lstat,
    	"Stat":os.Stat,
    	"Pipe":os.Pipe,
    	"FileMode":func(FileMode uint32) os.FileMode {return os.FileMode(FileMode)},
    },
}